# Numpy Operation in Python with Jupyter Nootbook

#### import Numpy

In [2]:
import numpy as np

#### Combining Arrays

#### Horizontal Stacks (hstack)

In [4]:
a = np.array([1 , 2 , 3])
b = np.array([4 , 5 , 6])

result = np.hstack((a , b))

print(result)

[1 2 3 4 5 6]


#### Vertical Stack (vstack)

In [5]:
a = np.array([1 , 2 , 3])
b = np.array([4 , 5 , 6])

result = np.vstack((a , b))

print(result)

[[1 2 3]
 [4 5 6]]


## Splitting Arrays

In [9]:
arr = np.array([1 , 2 , 3 , 4 , 5 , 6])

result = np.split(arr , 6)

print(result)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


## Search Functions

#### Find Index

In [ ]:
arr = np.array([10 , 20 , 30 , 40 , 50])

index = np.where(arr == 50)

print(index)

(array([4]),)


#### Search Sorted Position

In [28]:
arr = np.array([10 , 20 , 30 , 40 , 50])

position = np.searchsorted(arr , 30 , side='left')

print(position)

2


#### Sort Functions

In [32]:
arr = np.array([50 , 30 , 300 , 20 , 10])

print(np.sort(arr))

[ 10  20  30  50 300]


## Aggregating & Statistical Functions

In [38]:
arr = np.array([10 , 20 , 30 , 40 , 50])

print("sum:" , np.sum(arr))
print("mean:" , np.mean(arr))
print("Median:" , np.median(arr))
print("max:" , np.max(arr))
print("min:", np.min(arr))

sum: 150
mean: 30.0
Median: 30.0
max: 50
min: 10


#### Filter Arrays ( Boolean Indexing )

In [42]:
arr = np.array([10 , 20 , 30 , 40 , 50])

result = arr[arr > 35]

print(result)

[40 50]


#### Multiple Condition

In [44]:
arr = np.array([10 , 20 , 30 , 40 , 50])

result = arr[(arr > 20) & (arr < 50)]

print(result)

[30 40]


#### Masking Arrays

In [49]:
arr = np.array([10 , 20 , 30 , 40 , 50])

mask = arr > 20

print(mask)

filterd = arr[mask]

print(filterd)

[False False  True  True  True]
[30 40 50]


#### Reshaping Arrays

##### Convert array dimensions without changing data.

1D to 3D

In [54]:
arr = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80])

result = arr.reshape(2 , 2 , 2)

print(result)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


1D to 2D

In [57]:
arr = np.array([10 , 20 , 30 , 40])

result = arr.reshape(2 , 2)

print(result)

[[10 20]
 [30 40]]


In [63]:
arr = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

result = arr.reshape(8)

print(result)

[10 20 30 40 50 60 70 80]


#### Array Broadcasting

In [66]:
a = np.array([[1] , [2] , [3] , [4]])

b = np.array([10 , 20 , 30])

result = a + b

print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]
