# Numpy Array and Operations

#### Numpy is Numerical Python. It is a Powerful Python librery used for numerical computating , mathemetical operations , data analysis , and working with mutidimensional arrays.

In [1]:
import numpy as np

In [4]:
arr = np.array([10 , 20 , 30 , 40 , 50])
print(arr)

[10 20 30 40 50]


#### 2D Array

In [5]:
arr = np.array([[1 , 2 , 3], [4 , 5 , 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


#### 3D Arrays

In [6]:
arr = np.array([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7  , 8]]])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Special Array Creation

In [7]:
arr = np.zeros((3 , 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Ones

In [8]:
arr = np.ones((2 , 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Identity Matrix

In [9]:
arr = np.eye(4)

print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Range

In [10]:
arr = np.arange(1 , 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## Indexing in Numpy

#### Indexing is used to access a specific element from an array.

#### 1D Array

In [12]:
arr = np.array([10 , 20 , 30 , 40])

print(arr[0])
print(arr[-1])

10
40


#### 2D Array

In [16]:
arr = np.array([
  [1 , 2 , 3],
  [4  , 5 , 6]
])

print(arr[0][0])
print(arr[1][2])
print(arr[1 , 2])

1
6
6


### 3D Array

In [15]:
arr = np.array([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7  , 8]]])

print(arr[0 , 0 , 0])

1


## Slicing in Numpy

#### Slicing extracts multiple element from an array.

#### 1D Array

In [19]:
arr = np.array([10 , 20 , 30 , 40 , 50 , 60])

print(arr[1:4])

print(arr[:4])

print(arr[3:])

[20 30 40]
[10 20 30 40]
[40 50 60]


#### 2D Array

In [21]:
arr = np.array([[10 , 20 , 30] , [40 , 50 , 60]])

print(arr[0:2])

print(arr[0:2 , 1:3])

[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]]


#### 3D Array

Syntax : [depth , row , column]

depth -> Layer Number
row   -> Rows Number
column-> column Number

In [31]:
arr = np.array([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7  , 8]]])

print(arr[0])
print(arr[1])
print(arr[0 , 0])
print(arr[1 , 0])
print(arr[0 , 0 , 0])
print(arr[: , : , ::-1])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[1 2]
[5 6]
1
[[[2 1]
  [4 3]]

 [[6 5]
  [8 7]]]


#### Mathemetical Operation

#### Numpy perform mathemetical Calculations directly on array.

In [35]:
a = np.array([1 , 2 , 3])
b = np.array([4 , 5 , 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(np.sqrt(a))
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]
[1 4 9]
